/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientBookingsRouteImport } from './routes/client/bookings'
import { Route as ClientBookRouteImport } from './routes/client/book'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportingRouteImport } from './routes/admin/reporting'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSessionsIndexRouteImport } from './routes/admin/sessions.index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings.index'
import { Route as AdminSessionsScheduleRouteImport } from './routes/admin/sessions.schedule'
import { Route as AdminSessionsNewRouteImport } from './routes/admin/sessions.new'
import { Route as AdminSessionsSessionIdRouteImport } from './routes/admin/sessions.$sessionId'
import { Route as AdminClientsNewRouteImport } from './routes/admin/clients.new'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin/clients.$clientId'
import { Route as AdminBookingsNewRouteImport } from './routes/admin/bookings.new'
import { Route as AdminSessionsEditTypeIdRouteImport } from './routes/admin/sessions.edit.$typeId'
import { Route as AdminSessionsEditSessionIdRouteImport } from './routes/admin/sessions.edit.$sessionId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookRoute = ClientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsIndexRoute = AdminSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsScheduleRoute = AdminSessionsScheduleRouteImport.update({
  id: '/sessions/schedule',
  path: '/sessions/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsNewRoute = AdminSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsSessionIdRoute = AdminSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsNewRoute = AdminBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsEditTypeIdRoute = AdminSessionsEditTypeIdRouteImport.update({
  id: '/sessions/edit/$typeId',
  path: '/sessions/edit/$typeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsEditSessionIdRoute =
  AdminSessionsEditSessionIdRouteImport.update({
    id: '/sessions/edit/$sessionId',
    path: '/sessions/edit/$sessionId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/book-call': typeof BookCallRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/book': typeof ClientBookRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/sessions/new': typeof AdminSessionsNewRoute
  '/admin/sessions/schedule': typeof AdminSessionsScheduleRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/sessions/edit/$sessionId': typeof AdminSessionsEditSessionIdRoute
  '/admin/sessions/edit/$typeId': typeof AdminSessionsEditTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/book-call': typeof BookCallRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/book': typeof ClientBookRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/sessions/new': typeof AdminSessionsNewRoute
  '/admin/sessions/schedule': typeof AdminSessionsScheduleRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/admin/sessions/edit/$sessionId': typeof AdminSessionsEditSessionIdRoute
  '/admin/sessions/edit/$typeId': typeof AdminSessionsEditTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/book-call': typeof BookCallRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/book': typeof ClientBookRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/sessions/new': typeof AdminSessionsNewRoute
  '/admin/sessions/schedule': typeof AdminSessionsScheduleRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/sessions/edit/$sessionId': typeof AdminSessionsEditSessionIdRoute
  '/admin/sessions/edit/$typeId': typeof AdminSessionsEditTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blocked'
    | '/book-call'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/reporting'
    | '/admin/settings'
    | '/client/book'
    | '/client/bookings'
    | '/client/dashboard'
    | '/sessions/$sessionId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/sessions/$sessionId'
    | '/admin/sessions/new'
    | '/admin/sessions/schedule'
    | '/admin/bookings/'
    | '/admin/clients/'
    | '/admin/sessions/'
    | '/admin/sessions/edit/$sessionId'
    | '/admin/sessions/edit/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blocked'
    | '/book-call'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/reporting'
    | '/admin/settings'
    | '/client/book'
    | '/client/bookings'
    | '/client/dashboard'
    | '/sessions/$sessionId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/sessions/$sessionId'
    | '/admin/sessions/new'
    | '/admin/sessions/schedule'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/sessions'
    | '/admin/sessions/edit/$sessionId'
    | '/admin/sessions/edit/$typeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blocked'
    | '/book-call'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/reporting'
    | '/admin/settings'
    | '/client/book'
    | '/client/bookings'
    | '/client/dashboard'
    | '/sessions/$sessionId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/sessions/$sessionId'
    | '/admin/sessions/new'
    | '/admin/sessions/schedule'
    | '/admin/bookings/'
    | '/admin/clients/'
    | '/admin/sessions/'
    | '/admin/sessions/edit/$sessionId'
    | '/admin/sessions/edit/$typeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlockedRoute: typeof BlockedRoute
  BookCallRoute: typeof BookCallRoute
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/book': {
      id: '/client/book'
      path: '/book'
      fullPath: '/client/book'
      preLoaderRoute: typeof ClientBookRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/': {
      id: '/admin/sessions/'
      path: '/sessions'
      fullPath: '/admin/sessions/'
      preLoaderRoute: typeof AdminSessionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/schedule': {
      id: '/admin/sessions/schedule'
      path: '/sessions/schedule'
      fullPath: '/admin/sessions/schedule'
      preLoaderRoute: typeof AdminSessionsScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/new': {
      id: '/admin/sessions/new'
      path: '/sessions/new'
      fullPath: '/admin/sessions/new'
      preLoaderRoute: typeof AdminSessionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/$sessionId': {
      id: '/admin/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/admin/sessions/$sessionId'
      preLoaderRoute: typeof AdminSessionsSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/new': {
      id: '/admin/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminBookingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/edit/$typeId': {
      id: '/admin/sessions/edit/$typeId'
      path: '/sessions/edit/$typeId'
      fullPath: '/admin/sessions/edit/$typeId'
      preLoaderRoute: typeof AdminSessionsEditTypeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/edit/$sessionId': {
      id: '/admin/sessions/edit/$sessionId'
      path: '/sessions/edit/$sessionId'
      fullPath: '/admin/sessions/edit/$sessionId'
      preLoaderRoute: typeof AdminSessionsEditSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminBookingsNewRoute: typeof AdminBookingsNewRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
  AdminSessionsSessionIdRoute: typeof AdminSessionsSessionIdRoute
  AdminSessionsNewRoute: typeof AdminSessionsNewRoute
  AdminSessionsScheduleRoute: typeof AdminSessionsScheduleRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminSessionsIndexRoute: typeof AdminSessionsIndexRoute
  AdminSessionsEditSessionIdRoute: typeof AdminSessionsEditSessionIdRoute
  AdminSessionsEditTypeIdRoute: typeof AdminSessionsEditTypeIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminBookingsNewRoute: AdminBookingsNewRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
  AdminSessionsSessionIdRoute: AdminSessionsSessionIdRoute,
  AdminSessionsNewRoute: AdminSessionsNewRoute,
  AdminSessionsScheduleRoute: AdminSessionsScheduleRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminSessionsIndexRoute: AdminSessionsIndexRoute,
  AdminSessionsEditSessionIdRoute: AdminSessionsEditSessionIdRoute,
  AdminSessionsEditTypeIdRoute: AdminSessionsEditTypeIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientBookRoute: typeof ClientBookRoute
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookRoute: ClientBookRoute,
  ClientBookingsRoute: ClientBookingsRoute,
  ClientDashboardRoute: ClientDashboardRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlockedRoute: BlockedRoute,
  BookCallRoute: BookCallRoute,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
