/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientBookingsRouteImport } from './routes/client/bookings'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminReportingRouteImport } from './routes/admin/reporting'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminSessionsScheduleRouteImport } from './routes/admin/sessions.schedule'
import { Route as AdminSessionsNewRouteImport } from './routes/admin/sessions.new'
import { Route as AdminSessionsSessionIdRouteImport } from './routes/admin/sessions.$sessionId'
import { Route as AdminClientsNewRouteImport } from './routes/admin/clients.new'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin/clients.$clientId'
import { Route as AdminBookingsNewRouteImport } from './routes/admin/bookings.new'
import { Route as AdminSessionsEditTypeIdRouteImport } from './routes/admin/sessions.edit.$typeId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsScheduleRoute = AdminSessionsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminSessionsRoute,
} as any)
const AdminSessionsNewRoute = AdminSessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminSessionsRoute,
} as any)
const AdminSessionsSessionIdRoute = AdminSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AdminSessionsRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminBookingsNewRoute = AdminBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminSessionsEditTypeIdRoute = AdminSessionsEditTypeIdRouteImport.update({
  id: '/edit/$typeId',
  path: '/edit/$typeId',
  getParentRoute: () => AdminSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/sessions/new': typeof AdminSessionsNewRoute
  '/admin/sessions/schedule': typeof AdminSessionsScheduleRoute
  '/admin/sessions/edit/$typeId': typeof AdminSessionsEditTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/sessions/new': typeof AdminSessionsNewRoute
  '/admin/sessions/schedule': typeof AdminSessionsScheduleRoute
  '/admin/sessions/edit/$typeId': typeof AdminSessionsEditTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/sessions/new': typeof AdminSessionsNewRoute
  '/admin/sessions/schedule': typeof AdminSessionsScheduleRoute
  '/admin/sessions/edit/$typeId': typeof AdminSessionsEditTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blocked'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/unauthorized'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/reporting'
    | '/admin/sessions'
    | '/admin/settings'
    | '/client/bookings'
    | '/client/dashboard'
    | '/sessions/$sessionId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/sessions/$sessionId'
    | '/admin/sessions/new'
    | '/admin/sessions/schedule'
    | '/admin/sessions/edit/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blocked'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/unauthorized'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/reporting'
    | '/admin/sessions'
    | '/admin/settings'
    | '/client/bookings'
    | '/client/dashboard'
    | '/sessions/$sessionId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/sessions/$sessionId'
    | '/admin/sessions/new'
    | '/admin/sessions/schedule'
    | '/admin/sessions/edit/$typeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blocked'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/profile'
    | '/signup'
    | '/unauthorized'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/reporting'
    | '/admin/sessions'
    | '/admin/settings'
    | '/client/bookings'
    | '/client/dashboard'
    | '/sessions/$sessionId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/new'
    | '/admin/sessions/$sessionId'
    | '/admin/sessions/new'
    | '/admin/sessions/schedule'
    | '/admin/sessions/edit/$typeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlockedRoute: typeof BlockedRoute
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/schedule': {
      id: '/admin/sessions/schedule'
      path: '/schedule'
      fullPath: '/admin/sessions/schedule'
      preLoaderRoute: typeof AdminSessionsScheduleRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
    '/admin/sessions/new': {
      id: '/admin/sessions/new'
      path: '/new'
      fullPath: '/admin/sessions/new'
      preLoaderRoute: typeof AdminSessionsNewRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
    '/admin/sessions/$sessionId': {
      id: '/admin/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/admin/sessions/$sessionId'
      preLoaderRoute: typeof AdminSessionsSessionIdRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/bookings/new': {
      id: '/admin/bookings/new'
      path: '/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminBookingsNewRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/sessions/edit/$typeId': {
      id: '/admin/sessions/edit/$typeId'
      path: '/edit/$typeId'
      fullPath: '/admin/sessions/edit/$typeId'
      preLoaderRoute: typeof AdminSessionsEditTypeIdRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
  }
}

interface AdminBookingsRouteChildren {
  AdminBookingsNewRoute: typeof AdminBookingsNewRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsNewRoute: AdminBookingsNewRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminClientsRouteChildren {
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminSessionsRouteChildren {
  AdminSessionsSessionIdRoute: typeof AdminSessionsSessionIdRoute
  AdminSessionsNewRoute: typeof AdminSessionsNewRoute
  AdminSessionsScheduleRoute: typeof AdminSessionsScheduleRoute
  AdminSessionsEditTypeIdRoute: typeof AdminSessionsEditTypeIdRoute
}

const AdminSessionsRouteChildren: AdminSessionsRouteChildren = {
  AdminSessionsSessionIdRoute: AdminSessionsSessionIdRoute,
  AdminSessionsNewRoute: AdminSessionsNewRoute,
  AdminSessionsScheduleRoute: AdminSessionsScheduleRoute,
  AdminSessionsEditTypeIdRoute: AdminSessionsEditTypeIdRoute,
}

const AdminSessionsRouteWithChildren = AdminSessionsRoute._addFileChildren(
  AdminSessionsRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminSessionsRoute: typeof AdminSessionsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminSessionsRoute: AdminSessionsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientDashboardRoute: ClientDashboardRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlockedRoute: BlockedRoute,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
